# Generated by Django 2.2.4 on 2019-09-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_total',
            field=models.DecimalField(decimal_places=199, default=0.0, max_digits=900),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item_total',
            field=models.DecimalField(decimal_places=199, default=0.0, max_digits=900),
        ),
    ]
